// <auto-generated />
using System;
using ATNetCoreTelegramBot.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ATNetCoreTelegramBot.Models.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ATNetCoreTelegramBot.Models.SchemaTelegram.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(1);

                    b.Property<int>("Ordering")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_telegram.Channels.Name");

                    b.ToTable("Channels", "telegram");
                });

            modelBuilder.Entity("ATNetCoreTelegramBot.Models.SchemaTelegram.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(1);

                    b.Property<int>("Ordering")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_telegram.Groups.Name");

                    b.ToTable("Groups", "telegram");
                });

            modelBuilder.Entity("ATNetCoreTelegramBot.Models.SchemaTelegram.TelegramUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnOrder(0)
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool?>("CanJoinGroups")
                        .HasColumnType("bit")
                        .HasColumnOrder(7);

                    b.Property<bool?>("CanReadAllGroupMessages")
                        .HasColumnType("bit")
                        .HasColumnOrder(8);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("InsertDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(10);

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit")
                        .HasColumnOrder(5);

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnOrder(6);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnOrder(4);

                    b.Property<bool?>("SupportsInlineQueries")
                        .HasColumnType("bit")
                        .HasColumnOrder(9);

                    b.Property<long>("TelegramID")
                        .HasColumnType("bigint")
                        .HasColumnOrder(1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.HasIndex("TelegramID")
                        .IsUnique()
                        .HasDatabaseName("IX_telegram.Users.TelegramID");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_telegram.Users.UserName");

                    b.ToTable("TelegramUsers", "telegram");
                });
#pragma warning restore 612, 618
        }
    }
}
