//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATNetCoreTelegramBot.Resource.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATNetCoreTelegramBot.Resource.Messages.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values of the Fields {1} and {2} must be equal!.
        /// </summary>
        public static string Compare {
            get {
                return ResourceManager.GetString("Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully backed up by the file..
        /// </summary>
        public static string DatabaseBackup {
            get {
                return ResourceManager.GetString("DatabaseBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field value is already exist! Please choose another one..
        /// </summary>
        public static string DuplicateError {
            get {
                return ResourceManager.GetString("DuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, your email address has not been confirmed so far! Please check your e-mail account to confirm it..
        /// </summary>
        public static string Error002 {
            get {
                return ResourceManager.GetString("Error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, you are not able to log into the database! Please contact the database administrators..
        /// </summary>
        public static string Error003 {
            get {
                return ResourceManager.GetString("Error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} The page uses this template! So you can not delete it..
        /// </summary>
        public static string Error007 {
            get {
                return ResourceManager.GetString("Error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you have not entered the correct password right now!.
        /// </summary>
        public static string Error008 {
            get {
                return ResourceManager.GetString("Error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and / or password is not correct! Please try again.
        /// </summary>
        public static string Error009 {
            get {
                return ResourceManager.GetString("Error009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify file for uploading!.
        /// </summary>
        public static string Error100 {
            get {
                return ResourceManager.GetString("Error100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information has been used elsewhere, so you can not remove it!.
        /// </summary>
        public static string Error101 {
            get {
                return ResourceManager.GetString("Error101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is in use! So you can not delete it....
        /// </summary>
        public static string Error110 {
            get {
                return ResourceManager.GetString("Error110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Data Has Been Created Previously!.
        /// </summary>
        public static string Error200 {
            get {
                return ResourceManager.GetString("Error200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on sending or receiving data!.
        /// </summary>
        public static string ErrorOnJson {
            get {
                return ResourceManager.GetString("ErrorOnJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new password has been successfully registered..
        /// </summary>
        public static string Information001 {
            get {
                return ResourceManager.GetString("Information001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information has been successfully recorded..
        /// </summary>
        public static string Information002 {
            get {
                return ResourceManager.GetString("Information002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation of updating subsystem information, sections, and activities was done successfully..
        /// </summary>
        public static string Information003 {
            get {
                return ResourceManager.GetString("Information003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your photo has been successfully uploaded.
        /// </summary>
        public static string Information004 {
            get {
                return ResourceManager.GetString("Information004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your resume has been successfully sent.
        /// </summary>
        public static string Information005 {
            get {
                return ResourceManager.GetString("Information005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file was successfully saved at the time of {0}..
        /// </summary>
        public static string Information006 {
            get {
                return ResourceManager.GetString("Information006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Data Created Successfully..
        /// </summary>
        public static string Information007 {
            get {
                return ResourceManager.GetString("Information007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file uploaded successfully..
        /// </summary>
        public static string Information010 {
            get {
                return ResourceManager.GetString("Information010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file deleted successfully..
        /// </summary>
        public static string Information011 {
            get {
                return ResourceManager.GetString("Information011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on sending/receiving Data!.
        /// </summary>
        public static string JsonRequestError {
            get {
                return ResourceManager.GetString("JsonRequestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading... Please Wait!.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of {0} could not be more than {1}!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Question001 {
            get {
                return ResourceManager.GetString("Question001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {1} and {2}!.
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You did not specify a valid cell phone number!.
        /// </summary>
        public static string RegularExpressionForCellPhoneNumber {
            get {
                return ResourceManager.GetString("RegularExpressionForCellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer or double numbers!.
        /// </summary>
        public static string RegularExpressionForDouble {
            get {
                return ResourceManager.GetString("RegularExpressionForDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid email address!.
        /// </summary>
        public static string RegularExpressionForEmail {
            get {
                return ResourceManager.GetString("RegularExpressionForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 1 - 100 characters..
        /// </summary>
        public static string RegularExpressionForFileName {
            get {
                return ResourceManager.GetString("RegularExpressionForFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer numbers!.
        /// </summary>
        public static string RegularExpressionForInteger {
            get {
                return ResourceManager.GetString("RegularExpressionForInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not valid!.
        /// </summary>
        public static string RegularExpressionForMoney {
            get {
                return ResourceManager.GetString("RegularExpressionForMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains 10 digits..
        /// </summary>
        public static string RegularExpressionForNationalCode {
            get {
                return ResourceManager.GetString("RegularExpressionForNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 8 - 40 characters..
        /// </summary>
        public static string RegularExpressionForPassword {
            get {
                return ResourceManager.GetString("RegularExpressionForPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you should use numbers between 0.00 to 100.00!.
        /// </summary>
        public static string RegularExpressionForPercentage {
            get {
                return ResourceManager.GetString("RegularExpressionForPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid url address!.
        /// </summary>
        public static string RegularExpressionForUrl {
            get {
                return ResourceManager.GetString("RegularExpressionForUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is invalid! {0} must contains _ and/or upercase and lowercase English character and/or number between 0 - 9 and its length must be between 6 - 20 characters..
        /// </summary>
        public static string RegularExpressionForUsername {
            get {
                return ResourceManager.GetString("RegularExpressionForUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the field {0} you are just allowed to use integer numbers &gt;=0.
        /// </summary>
        public static string RegularExpressionForZeroOrUnsignedInteger {
            get {
                return ResourceManager.GetString("RegularExpressionForZeroOrUnsignedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} is required!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required!.
        /// </summary>
        public static string RequiredGeneral {
            get {
                return ResourceManager.GetString("RequiredGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your information saved successfully..
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an item....
        /// </summary>
        public static string SelectAnItem {
            get {
                return ResourceManager.GetString("SelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be between {2} and {1} characters!.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred! Please contact the system administrator..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value {0} is not valid!.
        /// </summary>
        public static string UnvalidatedValue {
            get {
                return ResourceManager.GetString("UnvalidatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can select an item....
        /// </summary>
        public static string YouCanSelectAnItem {
            get {
                return ResourceManager.GetString("YouCanSelectAnItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select an item!.
        /// </summary>
        public static string YouShouldSelectAnItem {
            get {
                return ResourceManager.GetString("YouShouldSelectAnItem", resourceCulture);
            }
        }
    }
}
